### ISSUE TITLE
Issue with Cluster module

### ISSUE THREAD

**Issue by kushalkh** [thibaultcha/lua-cassandra#100]
Hi guys,

I'm facing a weird issue with the cluster module. I implemented it exactly like it's described in the intro.lua example here: http://thibaultcha.github.io/lua-cassandra/examples/intro.lua.html

Now it works perfectly the first time the code is executed after restarting openresty but all subsequent requests just hang and i see this type of errors in error log on openresty: "2017/06/05 14:53:10 [alert] 27027#27027: worker process 27205 exited on signal 11" for all those subsequent requests that hang.

When i restart openresty again and try it, the first request again works fine and subsequent ones hang again. What could i be doing wrong here?

Thanks much.

**Comment by thibaultcha** [comment]
@kushalkh Hi,

Would you mind doing the following:
- pasting the code you wrote here
- trying with the master branch of this module. You can install the master branch with: `luarocks make https://raw.githubusercontent.com/thibaultcha/lua-cassandra/master/lua-cassandra-dev-0.rockspec`

Thanks!

**Comment by kushalkh** [comment]
@thibaultcha 

Hi, 
I think the issue was that i was not using init_by_lua directive to open the connection and keep it open. Using that resolved it. Thanks for looking.
