### ISSUE TITLE
[feature] expose various ssl params for luasec (feature request)

### ISSUE THREAD

**Issue by craveica** [thibaultcha/lua-cassandra#106]
Our C* clusters support only TLSv1.2, but the driver is hard coded to use TLSv1. It would be nice to have some config options for ssl (protocol, ciphers, curves, etc) when using in init_by_lua*.

**Comment by thibaultcha** [comment]
I agree. Will you contribute a patch for this feature? Simply passing it in the `opts` table of the proxy function should be enough!

**Comment by craveica** [comment]
I think I will wait for https://github.com/openresty/lua-nginx-module/issues/1020
