### ISSUE TITLE
Implement load balancing and retry policies

### ISSUE THREAD

**Issue by thibaultCha** [thibaultCha/lua-cassandra#11]
Like jbochi/lua-resty-cassandra#21, we don't support load balancing policies (nor retry policies).

Currently retry policies are a priority because of Mashape/kong#660. However, the driver is subject to more constraints than its Datastax official counterparts (Node.js, Python, Java) since it must run in an Openresty context. I started a discussion on the [Openresty Google group](https://groups.google.com/forum/#!topic/openresty-en/Oz2qySkUxBs) to get feedback on the limitations due to such constraints before implementing it.

**Comment by poll0rz** [comment]
+1
