### ISSUE TITLE
wrap existing C driver in lua?

### ISSUE THREAD

**Issue by smanolache** [thibaultCha/lua-cassandra#14]
Would it be simpler to wrap in lua the existing cassandra driver written in C? (C++ actually, but it's interface is plain C.) For reference: https://github.com/datastax/cpp-driver

I am aware that this would complicate the portability but it would also profit from the large datastax community.

**Comment by thibaultCha** [comment]
We need to leverage the openresty cosocket API and the portability is indeed another issue.

**Comment by thibaultCha** [comment]
Oh, and the rewrite allows for cluster awareness, which is available through ngx.shared.DICT, hence even if we wrap parts of the C driver, we need custom Lua code on top. At the end this is not a big deal.
