### ISSUE TITLE
[Kong 2.0.4][Cassandra cluster] shm at full capacity

### ISSUE THREAD

**Issue by rishabh-gupta2** [thibaultcha/lua-cassandra#143]
@thibaultcha 
I'm using **Kong 2.0.4** along with **Cassandra** as a database.
Referring [kong/db/strategies/cassandra/connector.lua](https://github.com/Kong/kong/blob/50b8405d02a3bcdf070033632ef0521db1219371/kong/db/strategies/cassandra/connector.lua#L138) and [lib/resty/cassandra/cluster.lua](https://github.com/thibaultcha/lua-cassandra/blob/master/lib/resty/cassandra/cluster.lua#L340 ) :

lua-cassandra uses a shm for various operations (`peers`, `prepare_and_execute`, etc.). Few of these methods internally uses `shm:safe_set` which does not evict items and directly throws error if no memory available [[Ref](https://github.com/openresty/lua-nginx-module/#ngxshareddictsafe_set)] 

I'm observing a consistent increase for memory occupied for this shm. It reaches close to 100 percent within a span of 45-60 days. _(As of now, I am rotating instances when it reaches close to 100 percent as a temporary solution)_

Few questions regarding this behaviour:
1. Is this consistent increase expected? Is this value never expected to go down?
2. Possible reasons for this increase.
3. If this shm is at full capacity, will it increase the request error rate or latencies?
4. What factors to consider to tune the capacity for this shm?

**Comment by thibaultcha** [comment]
Hi,
The shm also calls `:set()` and `:get()`, both of which call ngx_http_lua_shdict_expire to free-up space based on the LRU queue. Are you using Kong in a K8S environment or other, in which C* containers are frequently being rotated? Is `cassandra_refresh_frequency` still set to 60s and/or have you tried smaller and larger intervals to see if the shm fills up faster or slower? How are you monitoring the memory allocated by the shm? What errors are you experiencing when the shm is full?

**Comment by rishabh-gupta2** [comment]
> Are you using Kong in a K8S environment or other, in which C* containers are frequently being rotated?

Yes, I'm using Kong in a K8s environment but the containers are not being rotated frequently. Rotation of containers usually occur only in case of manual rotation when observing low available memory for `kong_cassandra` shm. This manual rotation is done only as a temporary solution as I'm not sure of the impact when the capacity is full.

> Is cassandra_refresh_frequency still set to 60s and/or have you tried smaller and larger intervals to see if the shm fills up faster or slower?

I'm using `cassandra_refresh_frequency` as 300s from the start. Haven't yet played around with this to check its effects on shm memory.

> How are you monitoring the memory allocated by the shm?

Via prometheus metrics. [[Ref](https://github.com/Kong/kong-plugin-prometheus/blob/d125bf35ce2b39426609ce09c94ef21771279314/kong/plugins/prometheus/exporter.lua#L48)]. Using this [Grafana dashboard](https://grafana.com/grafana/dashboards/7424)

> What errors are you experiencing when the shm is full?

That's what I want to understand if there is any negative impact when this shm is full. It has never reached the state when it is full. When the capacity is around 95% full, I end up rotating the pods to reset it. Haven't observed any errors yet at 95% occupied state.

**Comment by thibaultcha** [comment]
shm memory metrics reported by the Grafana dashboard are collected via the PDK's [kong.node.get_memory_stats](https://docs.konghq.com/gateway-oss/2.3.x/pdk/kong.node/#kongnodeget_memory_statsunit-scale) which itself uses [ngx.shared.DICT.free_space](https://github.com/openresty/lua-nginx-module#ngxshareddictfree_space). As noted there, full shms are still subject to LRU eviction (in all non-safe read/write shm APIs as noted above). There should be no reason for rotating Kong instances based on the basis of this shm being full, at least none expected.
