### ISSUE TITLE
[Kong] mTLS two way auth db with cassandra

### ISSUE THREAD

**Issue by vgrimaldihub** [thibaultcha/lua-cassandra#146]
Hello everyone,

I'm trying to connect kong (2.4.0) with a Cassandra 3.11.11 using two way auth setting require_client_auth= true (in cassandra).  But I can't see any kong config to set kong certs during cassandra handshake.

I also struggle to see how kong defines its handshake, can’t really work on the lua.

**It’s not supported by lua-cassandra behind? I sould configure something on a nginx custom config?**

I think kong just send me a generic error for handshake:
/usr/local/share/lua/5.1/kong/cmd/start.lua:33: [Cassandra error] all hosts tried for query failed. 172.18.0.3: SSL handshake: sslv3 alert bad certificate.

Thanks for any help or advice.

**Comment by thibaultcha** [comment]
Hi,

Please report this issue to Kong - there is no mTLS support in OpenResty's cosockets, that is a Kong Gateway patch to OpenResty.
