### ISSUE TITLE
second request on the same connection before first response

### ISSUE THREAD

**Issue by smanolache** [thibaultcha/lua-cassandra#20]
Hello,

I've run a stress test on kong and I've noticed that several requests may be sent on the same connection before the response to the first request arrives. As the stream-id is hard-coded in the lua-cassandra driver all outstanding requests have the same stream-id, namely zero, which, I suppose, violates the protocol specification.

I suppose this happens when the client decides that there's a response timeout and stops waiting for the server response. It seems that the connection is not closed in this case and a subsequent request may be sent on the same connection.

I've attached a network capture file.
[db2.zip](https://github.com/thibaultCha/lua-cassandra/files/60272/db2.zip)

**Comment by thibaultCha** [comment]
The stream id is optional and only implemented for asynchronous operations. Since the cosocket API is synchronous, this library ignores it. Maybe it could be implemented but I haven't looked into it. Is Kong or lua-cassandra complaining? Is this causing queries to receive the wrong response?

If you are putting this driver under load, then you should maybe the socket pool size and eventually the sockets timeout to avoid this.

**Comment by thibaultCha** [comment]
I should reformulate because I got confused in my own reply: the stream id is not implemented because it is optional and this library assumes that the load will never exceed the socket pool size, and the calls are synchronous. As I said, it could probably be implemented but I did not look into it.

**Comment by thibaultCha** [comment]
I just had a look to the specs and I think this could easily be implemented. Thanks for reporting this. Do you have a minimal use case to reproduce this that the implementation can be tested against?

**Comment by smanolache** [comment]
On 2015-12-12 23:34, Thibault Charbonnier wrote:
> I just had a look to the specs and I think this could easily be
> implemented. Thanks for reporting this. Do you have a minimal use case
> to reproduce this that the implementation can be tested against?

The use case is:

Only two plugins activated: acl and key-auth.

A single consumer is defined.

A single white-list is configured in the acl plugin. The consumer is 
added to it.

key-auth configured with a key for the consumer.

An api is configured in kong, it just forwards the request to a dummy 
backend.

Kong is on one machine, the backend on another machine. Then there is a 
cluster of four cassandra machines running cassandra 2.1.x (2.1.7 or 
2.1.11, I don't remember) using the gossip snitch.

Additionally I have two injector machines. The load generated by the 
injectors is initially 200 req/s, I keep it for three minutes, then I 
raise to 400 req/s, keep it for 3 minutes, etc, up to 3000 req/sec.

The database cache configured in kong is the default one, 5 seconds. As 
you can see from the network capture the requests are made to the plugin 
table, looking for the configurations of the two activated plugins.

I can't answer your question if kong/the driver complains about not 
receiving the good responses from the cassandra server. I'm getting 
between 2 and 4% errors (HTTP 500 internal server error from kong), but 
what I mostly see in the logs are cassandra timeouts.

Check the network capture file I've sent in the first message (it's a 
zipped pcap file, you can see it in wireshark). You'll see the second 
request going to the server before the first response arrives. It's just 
a snippet from a 195kB capture file that has many more examples of the 
same type (I can send you the whole capture file if you want). You'll 
notice that the second request fires more than 5 seconds after the 
first, so I'm almost sure that the client considers that the first 
request timed out and abandoned it without closing the session/socket.

Regards,
Sorin

**Comment by smanolache** [comment]
> I'm almost sure that the client considers that the first
> request timed out and abandoned it without closing the session/socket.

Sorry, when I say "client" I mean it from the cassandra server 
perspective. So the "client" is kong/the lua-cassandra driver.

**Comment by smanolache** [comment]
> Kong is on one machine, the backend on another machine. Then there is a
> cluster of four cassandra machines running cassandra 2.1.x (2.1.7 or
> 2.1.11, I don't remember) using the gossip snitch.

I've forgotten to mention: I'm using a patched version of kong and 
lua-cassandra that allows me to specify the consistency level. (We've 
spoken about it, I've sent you the patches but they were rejected 
because you'll soon release a new version of the driver.)

I'm using LOCAL_QUORUM, i.e. three of my four nodes must answer so the 
timeouts are more likely than if I used a consistency level of ONE.

You can see the consistency level in the request frames of the network 
capture. (For example in packet 10, the 0x0006 short at offset 28 of the 
83-byte TCP data.)

**Comment by thibaultCha** [comment]
I wasn't talking about a Kong usecase but a usecase with lua-cassandra itself, as the issue is not with Kong. I'll try to setup one and reproduce. The fact that you are using LOCAL_QUORUM for consistency is probably why you are seeing this, because sockets are timing out more frequently, and the driver uses the cosocket API, which re-uses a pool of sockets. So as a short term solution, like I suggested, you could increase the timeout and the pool size.
