### ISSUE TITLE
Improve the error messagges

### ISSUE THREAD

**Issue by thefosk** [thibaultCha/lua-cassandra#27]
Currently most error messages have the following line `NoHostAvailableError`, which is very confusing because it implies that the server is not reachable, while in reality it couldn't be anything else, like an invalid SSL cert path:

````
Cassandra error: NoHostAvailableError: All hosts tried for query failed. 127.0.0.1:9042: SocketError: error loading CA locations (No such file or directory) for socket with peer 127.0.0.1:9042.
```

**Comment by thibaultCha** [comment]
Yes, it's in the plans
