### ISSUE TITLE
Cassandra custom port is replaced by default port at some point

### ISSUE THREAD

**Issue by allisthere2love** [thibaultCha/lua-cassandra#47]
When I'm using a cassandra custom port (not 9042) and it's a cassandra cluster, the module gets "lost" at some point and tries to use the default port.

I was able to replicate the problem in the following scenario:
1 - 2 hosts (let's call it A and B), each one running 2 Cassandras (let's call it A1, B1, A2 and B2).
2 - One cluster is composed by A1 and B1 using default port, 9042
3 - One cluster is composed by A2 and B2 using custom port, 39044.

In this scenario, when I run a simple lua module to create a keyspace, table, insert some data and then select it, it only performs the first operation in the correct cluster (the one using custom ports). After that, seems it falls back to the default port and then get a "bad credentials" or a "missing column_family" error.
If I'm running a single node cassandra with custom ports there's no error.

To validate the problem, I moved the A2-B2 cluster to hosts that doesn't have Cassandra running in the default port. Then it all worked well.

**Comment by thibaultCha** [comment]
Thanks for investigating this! So, as we discussed privately, the proposed patch for now is:

```diff
diff --git a/src/cassandra.lua b/src/cassandra.lua
index de83543..461a4ad 100644
--- a/src/cassandra.lua
+++ b/src/cassandra.lua
@@ -1136,7 +1136,7 @@ function Cassandra.refresh_hosts(options)
     end
 
     for _, row in ipairs(rows) do
-      local address = options.policies.address_resolution(row["rpc_address"])
+      local address = options.policies.address_resolution(row["rpc_address"], options.protocol_options.default_port)
       log.info("Adding host "..address)
       hosts[address] = {
         unhealthy_at = 0,
```

used in accordance with a defined `default_port` in the protocol options. I tested this locally on a 2 nodes cluster listening in 9043, with only one contact_point defined. Without this patch, the driver assumes the other node listens on `9042`.

Let me know how this patch goes on your end :)

**Comment by allisthere2love** [comment]
Hi, 
I was able to sucessfully connect to the cluster after I've apllied the suggested patch and defined the variable in my test module.

Now I'm checking how to pass this config in Kong.
