### ISSUE TITLE
socket time out when reading large amount of data

### ISSUE THREAD

**Issue by JilinXie** [thibaultCha/lua-cassandra#53]
Hi, I'm trying to requesting all data from a table, which contains about 19000 rows.
session:execute("select * from table", nil, {page_size=1000, auto_paging=true})

With the default page_size of 1000,  I found nginx logs such error:

- lua tcp socket read timed out, client: 127.0.0.1, server: , request: "GET / HTTP/1.1",...
-  kevent() reported about an closed connection (54: Connection reset by peer), client: 127.0.0.1,... 

But if I cange page_size to 20000, no socket timeout occurs.

I'm trying to understand why this happens. And I'm not sure if this is a problem about my cassandra or my misuse of this lib. 
So, any ideas

**Comment by thibaultCha** [comment]
Were you able to resolve this?

**Comment by thibaultCha** [comment]
Well, considering this resolved then; especially since the 1.0.0 release which rewrites this library. Feel free to re-open if the issue persists and if you have some more details about it.
