### ISSUE TITLE
Incomplete data on fetching blob from database

### ISSUE THREAD

**Issue by architm21** [thibaultcha/lua-cassandra#74]
partial data is fetched from db , on blob type. Is there limits on size of data from a column.

**Comment by thibaultcha** [comment]
Not that I know of. Could you provide a minimal and standalone example so I can reproduce this on my side? Also, please provide detailed information about your environment such as the Lua/LuaJIT or OpenResty version and the Cassandra version you are using.

**Comment by architm21** [comment]
Thank you for the quick reply. Issue was solved , this seemed the issue was caused due to some other problems.
