### ISSUE TITLE
sbin/nginx  -s reload ,failed get data

### ISSUE THREAD

**Issue by zhenzhenyang** [thibaultcha/lua-cassandra#80]
hi ,I reload the nginx,can't get data,there is none logs in nginx logs. I must stop nginx and start nginx 。

 curl 'http://10.10.121.103:8800/cassandra'
{"1":{"vt":"1","version":"1.2.21","chnname":"动漫","videover":"4","userts":"20161129170902","uuid":"307c5483d8cc4eaca037ef7823c4063c","resolution":"1280*720","playorder":"1","logdate":"2016-11-29","osversion":"4.4.2","ti":"0","ip":"113.98.233.193","action":"5","endtime":1480410557000,"sourceid":"30","albumname":"小公主中文版","timelength":"660","chnid":"1000003","blockmsec":"0","videoid":"574222500","position":"3","partner":"JS_CUCC","cpid":"1","pl":15,"srcid":"2","blocktype":"0","playoffset":"3","mac":"00:19:f0:00:00:17","albumid":"915032","begintime":1480410542000,"cdntype":"huawei"},"type":"ROWS","meta":{"has_more_pages":false/usr/local/openresty/nginx/sbin/nginx -c /usr/local/openresty/nginx/conf/nginx.conf -s reload
[root@10.10.121.103 cassandra]# curl 'http://10.10.121.103:8800/cassandra'
curl: (52) Empty reply from server
[root@10.10.121.103 cassandra]# curl 'http://10.10.121.103:8800/cassandra'
curl: (52) Empty reply from server

**Comment by thibaultcha** [comment]
My hunch would be that this has to do with either the previous issue you described either with your usage of this library, and not the library itself.
