### ISSUE TITLE
Socket error!

### ISSUE THREAD

**Issue by hevan** [thibaultcha/lua-cassandra#94]
Can you help this error:

nginx: [error] init_by_lua error: /usr/local/openresty/lualib/cassandra/socket.lua:156: module 'socket' not found:
        no field package.preload['socket']
        no file '/path/to/src/socket.lua'
        no file '/path/to/src/socket/init.lua'
        no file '/usr/local/openresty/site/lualib/socket.lua'
        no file '/usr/local/openresty/site/lualib/socket/init.lua'
        no file '/usr/local/openresty/lualib/socket.lua'
        no file '/usr/local/openresty/lualib/socket/init.lua'
        no file './socket.lua'
        no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta2/socket.lua'
        no file '/usr/local/share/lua/5.1/socket.lua'
        no file '/usr/local/share/lua/5.1/socket/init.lua'
        no file '/usr/local/openresty/luajit/share/lua/5.1/socket.lua'
        no file '/usr/local/openresty/luajit/share/lua/5.1/socket/init.lua'
        no file '/usr/local/openresty/site/lualib/socket.so'
        no file '/usr/local/openresty/lualib/socket.so'
        no file './socket.so'
        no file '/usr/local/lib/lua/5.1/socket.so'
        no file '/usr/local/openresty/luajit/lib/lua/5.1/socket.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        /usr/local/openresty/lualib/cassandra/socket.lua:156: in function 'tcp'
        /usr/local/openresty/lualib/cassandra/init.lua:124: in function 'spawn_peer'
        /usr/local/openresty/lualib/resty/cassandra/cluster.lua:201: in function 'check_peer_health'
        /usr/local/openresty/lualib/resty/cassandra/cluster.lua:411: in function 'first_coordinator'
        /usr/local/openresty/lualib/resty/cassandra/cluster.lua:483: in function 'refresh'
        /usr/local/openresty/lualib/my_module.lua:16: in function 'init_cluster'
        init_by_lua:5: in main chunk

**Comment by thibaultcha** [comment]
Hi,

Please ensure you have either:

- Installed LuaSocket as well if you use this library in a context that do no support ngx_lua cosockets
- Only use this library in a cosocket-supported context

Thanks!
