### ISSUE TITLE
Planing to migrate from driver cassandra to lua-cassandra

### ISSUE THREAD

**Issue by leandromoreira** [thibaultcha/lua-cassandra#99]
Since the cassandra driver is not in active development we're planning to move on to this 🥇  awesome project.

I would like to know how different the API is from `cassandra`? [socket options](https://github.com/jbochi/lua-resty-cassandra#socket-methods) and [client](https://github.com/jbochi/lua-resty-cassandra#client-methods)

**Comment by thibaultcha** [comment]
Hi,

Glad to hear! The API for the single module is pretty much the same, but the usage of the clustering module differs a bit more, especially with the necessity to store the cluster instance as a local upvalue. Everything is documented online:

https://thibaultcha.github.io/lua-cassandra/

Depending on your cluster, you might want to look at the different load balancing policies and the desired level of consistency too.

**Comment by leandromoreira** [comment]
Thank you @thibaultcha, I'll be posting here any issues or advice for anyone in the same situation.

**Comment by thibaultcha** [comment]
FYI, today work is being done on the `refactor/perf+style` branch and will likely result in a more friendly cluster interface (I'd like to avoid the need for users to cache the instance themselves in an upvalue). But this is not before a while.

**Comment by thibaultcha** [comment]
Let's now close this, if you have further questions, feel free to open another issue.

**Comment by leandromoreira** [comment]
We postpone but we'll do it this quarter! I'll keep this up to date, thanks.

**Comment by thibaultcha** [comment]
@rafatio Yes indeed!

**Comment by rafatio** [comment]
@thibaultcha nice :)
Testing the cluster driver we are having some `could not refresh cluster: no host details for` and `no host details for`. Is those errors usual or there is something wrong?
